version: '2'
services:
    socleuser-app:
        image: socleuser
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://socleuser-postgresql:5432/socleUser
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    socleuser-postgresql:
        extends:
            file: postgresql.yml
            service: socleuser-postgresql
